development:
  dialect: postgres
  database: buffalo_poc_development
  user: postgres
  password: 286755fad04869ca523320acce0dc6a4
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/buffalo_poc_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/buffalo_poc_production?sslmode=disable"}}