consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  CreateQuotePayload:
    description: All quotes for a given user ID
    example:
      ID: 3.528801e+18
      Name: Voluptate accusantium nulla.
      Quote: Fugit adipisci non et et aliquid.
    properties:
      ID:
        description: ID of the user
        example: 3.528801e+18
        format: int64
        type: integer
      Name:
        description: User ID of quoter
        example: Voluptate accusantium nulla.
        type: string
      Quote:
        description: The actual quotes of the quoter
        example: Fugit adipisci non et et aliquid.
        type: string
    required:
    - Name
    - Quote
    title: CreateQuotePayload
    type: object
  CreateSuggestionPayload:
    description: All suggestions for a given user ID
    example:
      ShowID: Voluptatum pariatur incidunt illo ut.
      Suggester: Voluptates commodi quidem nihil quia doloribus ut.
      Title: Error ipsam totam.
    properties:
      ShowID:
        description: The ID of the show
        example: Voluptatum pariatur incidunt illo ut.
        type: string
      Suggester:
        description: Identity of suggester
        example: Voluptates commodi quidem nihil quia doloribus ut.
        type: string
      Title:
        description: The suggested title
        example: Error ipsam totam.
        type: string
    required:
    - ShowID
    - Suggester
    - Title
    title: CreateSuggestionPayload
    type: object
  Quote:
    description: All quotes for a given user ID (default view)
    example:
      ID: 3.528801e+18
      Name: Voluptate accusantium nulla.
      Quote: Fugit adipisci non et et aliquid.
    properties:
      ID:
        description: ID of the user
        example: 3.528801e+18
        format: int64
        type: integer
      Name:
        description: User ID of quoter
        example: Voluptate accusantium nulla.
        type: string
      Quote:
        description: The actual quotes of the quoter
        example: Fugit adipisci non et et aliquid.
        type: string
    title: 'Mediatype identifier: vnd.application.io/quote; view=default'
    type: object
  Quotes:
    description: A quote from the user database (default view)
    example:
      Quotes:
      - ID: 3.528801e+18
        Name: Voluptate accusantium nulla.
        Quote: Fugit adipisci non et et aliquid.
    properties:
      Quotes:
        description: Quote
        example:
        - ID: 3.528801e+18
          Name: Voluptate accusantium nulla.
          Quote: Fugit adipisci non et et aliquid.
        items:
          $ref: '#/definitions/Quote'
        type: array
    title: 'Mediatype identifier: vnd.application.io/quotes; view=default'
    type: object
  Suggestions:
    description: Suggestions media type (default view)
    example:
      Suggestions:
      - ShowID: Voluptatum pariatur incidunt illo ut.
        Suggester: Voluptates commodi quidem nihil quia doloribus ut.
        Title: Error ipsam totam.
      - ShowID: Voluptatum pariatur incidunt illo ut.
        Suggester: Voluptates commodi quidem nihil quia doloribus ut.
        Title: Error ipsam totam.
    properties:
      Suggestions:
        description: Suggestion
        example:
        - ShowID: Voluptatum pariatur incidunt illo ut.
          Suggester: Voluptates commodi quidem nihil quia doloribus ut.
          Title: Error ipsam totam.
        - ShowID: Voluptatum pariatur incidunt illo ut.
          Suggester: Voluptates commodi quidem nihil quia doloribus ut.
          Title: Error ipsam totam.
        items:
          $ref: '#/definitions/suggestion'
        type: array
    title: 'Mediatype identifier: vnd.application.io/suggestions; view=default'
    type: object
  suggestion:
    description: All suggestions for a given user ID
    example:
      ShowID: Voluptatum pariatur incidunt illo ut.
      Suggester: Voluptates commodi quidem nihil quia doloribus ut.
      Title: Error ipsam totam.
    properties:
      ShowID:
        description: The ID of the show
        example: Voluptatum pariatur incidunt illo ut.
        type: string
      Suggester:
        description: Identity of suggester
        example: Voluptates commodi quidem nihil quia doloribus ut.
        type: string
      Title:
        description: The suggested title
        example: Error ipsam totam.
        type: string
    title: suggestion
    type: object
info:
  description: Allows users to interact with Jupiter Broadcasting's shows
  title: The Kore of the Data
  version: ""
paths:
  /quotes:
    get:
      description: Returns all quotes in the quote database
      operationId: quote#list
      produces:
      - vnd.application.io/quotes
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Quotes'
        "401":
          description: Unauthorized
      schemes:
      - http
      summary: list quote
      tags:
      - quote
    post:
      description: |-
        Create a quote and add it to the database

        Required security scopes:
          * `api:write`
      operationId: quote#create
      parameters:
      - description: All quotes for a given user ID
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateQuotePayload'
      produces:
      - vnd.application.io/quotes
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Quotes'
        "401":
          description: Unauthorized
      schemes:
      - http
      security:
      - jwt:
        - api:write
      summary: create quote
      tags:
      - quote
  /quotes/{userId}:
    get:
      description: Returns all the quotes for a given person
      operationId: quote#list by ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - vnd.application.io/quote
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Quote'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list by ID quote
      tags:
      - quote
  /quotes/login:
    post:
      description: Login to the api
      operationId: quote#login
      responses:
        "204":
          description: No Content
          headers:
            Authorization:
              description: Generated JWT
              type: string
        "401":
          description: Unauthorized
      schemes:
      - http
      security:
      - BasicAuth: []
      summary: login quote
      tags:
      - quote
  /suggestion/:
    post:
      description: Create a new suggestion
      operationId: suggestion#create
      parameters:
      - description: All suggestions for a given user ID
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateSuggestionPayload'
      responses:
        "204":
          description: No Content
      schemes:
      - http
      summary: create suggestion
      tags:
      - suggestion
  /suggestion/{showId}:
    get:
      description: Return all suggestions for a given show ID
      operationId: suggestion#list
      parameters:
      - in: path
        name: showId
        required: true
        type: string
      produces:
      - vnd.application.io/suggestions
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Suggestions'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list suggestion
      tags:
      - suggestion
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NoContent:
    description: No Content
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Quotes'
  Unauthorized:
    description: Unauthorized
schemes:
- http
securityDefinitions:
  BasicAuth:
    description: Use client ID and client secret to authenticate
    type: basic
  jwt:
    description: |2-


      **Security Scopes**:
        * `api:read`: API read access
        * `api:write`: API write access
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
