consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Json:
    description: A quote from the user database (default view)
    example:
      quotes:
      - quote:
        - Accusantium nulla amet fugit adipisci non et.
        userID: Aliquid voluptatum.
    properties:
      quotes:
        description: quote
        example:
        - quote:
          - Accusantium nulla amet fugit adipisci non et.
          userID: Aliquid voluptatum.
        items:
          $ref: '#/definitions/quote'
        type: array
    title: 'Mediatype identifier: application/json; view=default'
    type: object
  quote:
    description: All quotes for a given user ID
    example:
      quote:
      - Accusantium nulla amet fugit adipisci non et.
      userID: Aliquid voluptatum.
    properties:
      quote:
        description: The actual quotes of the quoter
        example:
        - Accusantium nulla amet fugit adipisci non et.
        items:
          example: Accusantium nulla amet fugit adipisci non et.
          type: string
        type: array
      userID:
        description: User ID of quoter
        example: Aliquid voluptatum.
        type: string
    title: quote
    type: object
info:
  description: Allows users to interact with Jupiter Broadcasting's shows
  title: The Kore of the Data
  version: ""
paths:
  /quotes:
    get:
      description: Returns all quotes in the quote database
      operationId: quote#list
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Json'
      schemes:
      - http
      summary: list quote
      tags:
      - quote
  /quotes/{userId}:
    get:
      description: Returns all the quotes for a given person
      operationId: quote#list by ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Json'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list by ID quote
      tags:
      - quote
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Json'
schemes:
- http
swagger: "2.0"
