consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Json:
    description: A quote from the user database (default view)
    example:
      quotes:
      - ID: 5.271261e+18
        Name: Accusantium nulla amet fugit adipisci non et.
        Quote: Aliquid voluptatum.
    properties:
      quotes:
        description: quote
        example:
        - ID: 5.271261e+18
          Name: Accusantium nulla amet fugit adipisci non et.
          Quote: Aliquid voluptatum.
        items:
          $ref: '#/definitions/quote'
        type: array
    title: 'Mediatype identifier: application/json; view=default'
    type: object
  quote:
    description: All quotes for a given user ID
    example:
      ID: 5.271261e+18
      Name: Accusantium nulla amet fugit adipisci non et.
      Quote: Aliquid voluptatum.
    properties:
      ID:
        description: ID of the user
        example: 5.271261e+18
        format: int64
        type: integer
      Name:
        description: User ID of quoter
        example: Accusantium nulla amet fugit adipisci non et.
        type: string
      Quote:
        description: The actual quotes of the quoter
        example: Aliquid voluptatum.
        type: string
    title: quote
    type: object
info:
  description: Allows users to interact with Jupiter Broadcasting's shows
  title: The Kore of the Data
  version: ""
paths:
  /quotes:
    get:
      description: Returns all quotes in the quote database
      operationId: quote#list
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Json'
        "401":
          description: Unauthorized
      schemes:
      - http
      security:
      - BasicAuth: []
      summary: list quote
      tags:
      - quote
  /quotes/{userId}:
    get:
      description: Returns all the quotes for a given person
      operationId: quote#list by ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Json'
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      schemes:
      - http
      security:
      - BasicAuth: []
      summary: list by ID quote
      tags:
      - quote
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Json'
  Unauthorized:
    description: Unauthorized
schemes:
- http
securityDefinitions:
  BasicAuth:
    description: Use client ID and client secret to authenticate
    type: basic
swagger: "2.0"
